version: "3.7"
services:
    app:
        build:
            args:
                user: aruzhan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: canteen
        container_name: canteen-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - canteen
        ports:
            - '8001:80'

    db:
        image: mysql:8.0
        container_name: canteen-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: canteen
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - canteen
        ports:
            - '3307:3306'

    nginx:
        image: nginx:alpine
        container_name: canteen-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - canteen

networks:
    canteen:
        driver: bridge
